development:
  adapter: mysql2
  encoding: unicode
  database: rails
  pool: 5
  username: rails
  password: FPzJa1JOxL
  reconnect: true
  host: localhost

test:
  adapter: mysql2
  encoding: unicode
  database: rails
  pool: 5
  username: rails
  password: FPzJa1JOxL
  reconnect: true
  host: localhost

production:
  adapter: mysql2
  encoding: unicode
  database: rails
  pool: 5
  username: rails
  password: FPzJa1JOxL
  reconnect: true
  host: localhost

