development:
  adapter: postgresql
  encoding: unicode
  database: inove_development
  pool: 5
  username: postgres
  password: numero04
  reconnect: true
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: inove_development
  pool: 5
  username: postgres
  password: numero04
  reconnect: true
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: inove_development
  pool: 5
  username: postgres
  password: numero04
  reconnect: true
  host: localhost

