development:
  adapter: mysql2
  encoding: utf8
  database: rails
  pool: 5
  username: rails
  password: FPzJa1JOxL
  reconnect: true
  host: 162.243.240.109

test:
  adapter: mysql2
  encoding: utf8
  database: rails
  pool: 5
  username: rails
  password: FPzJa1JOxL
  reconnect: true
  host: 162.243.240.109

production:
  adapter: mysql2
  encoding: utf8
  database: rails
  pool: 5
  username: rails
  password: FPzJa1JOxL
  reconnect: true
  host: 162.243.240.109

